- name: Copier un fichier vers machines clientes
  hosts: all
  vars:
    fichier_source: /root/sdv.conf
    dossier_destination: /tmp
    proprietaire: root
    groupe: root
    permissions: '0755'

  tasks:
    - name: Copie du fichier
      copy:
        src: "{{ fichier_source }}"
        dest: "{{ dossier_destination }}"
        owner: "{{ proprietaire }}"
        group: "{{ groupe }}"
        mode: "{{ permissions }}"
