- name: Créer un fichier vide sur les clients distants
  hosts: all
  vars:
    nom_fichier: toto
  tasks:
    - name: Créer un fichier vide dans /tmp basé sur la variable
      ansible.builtin.file:
        path: "/tmp/{{ nom_fichier }}.log"
        state: touch
        mode: '0644'
