---
- name: Lancer les applications quiz sur tous les clients
  hosts: client1,client2,client3,client4
  become: yes
  gather_facts: no
  
  vars:
    app_directory: /opt/quiz-ansible
    app_port: 3000
    
  tasks:
    - name: Vérifier si l'application est déjà installée
      stat:
        path: "{{ app_directory }}/dist/index.html"
      register: app_installed
      
    - name: Arrêter les processus serve existants
      shell: pkill -f serve || true
      ignore_errors: yes
      when: app_installed.stat.exists
      
    - name: Attendre l'arrêt des processus
      pause:
        seconds: 2
      when: app_installed.stat.exists
      
    - name: Lancer l'application en arrière-plan
      shell: |
        cd {{ app_directory }}
        nohup serve -s dist -p {{ app_port }} > /dev/null 2>&1 &
        echo "Application lancée sur {{ inventory_hostname }}"
      register: launch_result
      when: app_installed.stat.exists
      
    - name: Afficher le résultat du lancement
      debug:
        msg: "{{ launch_result.stdout }}"
      when: app_installed.stat.exists
      
    - name: Attendre le démarrage
      pause:
        seconds: 3
      when: app_installed.stat.exists
      
    - name: Vérifier que l'application répond
      uri:
        url: "http://{{ ansible_host }}:{{ app_port }}"
        method: GET
        timeout: 10
      register: app_check
      delegate_to: localhost
      when: app_installed.stat.exists
      
    - name: Afficher le statut de l'application
      debug:
        msg: |
          ✅ Application {{ inventory_hostname }} : 
          URL: http://{{ ansible_host }}:{{ app_port }}
          Status: {{ app_check.status }}
      when: app_installed.stat.exists and app_check.status == 200
      
    - name: Afficher les applications non installées
      debug:
        msg: "❌ Application non installée sur {{ inventory_hostname }}"
      when: not app_installed.stat.exists
      
- name: Résumé final et tests
  hosts: localhost
  gather_facts: no
  
  tasks:
    - name: Tester toutes les applications
      uri:
        url: "http://{{ item }}:3000"
        method: GET
        timeout: 10
      loop:
        - 172.18.0.4  # client1
        - 172.18.0.5  # client2
        - 172.18.0.3  # client3
        - 172.18.0.2  # client4
      register: all_tests
      ignore_errors: yes
      
    - name: Afficher le résumé final
      debug:
        msg: |
          🎉 RÉSUMÉ FINAL - Applications Quiz Ansible
          
          {% for result in all_tests.results %}
          {% if result.status == 200 %}
          ✅ {{ result.item }}:3000 - OK ({{ result.status }})
          {% else %}
          ❌ {{ result.item }}:3000 - ERREUR
          {% endif %}
          {% endfor %}
          
          📋 Commandes pour tester :
          curl http://172.18.0.4:3000
          curl http://172.18.0.5:3000
          curl http://172.18.0.3:3000
          curl http://172.18.0.2:3000
          
          🌐 Ouvrir dans un navigateur :
          http://172.18.0.4:3000
          http://172.18.0.5:3000
          http://172.18.0.3:3000
          http://172.18.0.2:3000
