---
- name: Installation de nginx selon l'OS
  hosts: all
  become: yes
  tasks:
    - name: Installer nginx avec apt (Debian/Ubuntu)
      apt:
        name: nginx
        state: present
        update_cache: yes
      when: ansible_facts['os_family'] == "Debian"

    - name: Installer nginx avec yum (RedHat/CentOS/Rocky/SUSE)
      yum:
        name: nginx
        state: present
      when: ansible_facts['os_family'] == "RedHat" or ansible_facts['os_family'] == "Suse"

    - name: Afficher un message de confirmation
      debug:
        msg: "Nginx installé avec succès sur {{ inventory_hostname }}"
